name: Python application Tests

on:
  push:
    branches: [ "feature" ]  # Assuming you want to run tests on pushes to the main branch
  pull_request:
    branches: [ "feature" ]  # And on pull requests to the main branch

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Assuming you are using pytest for running your tests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: |
        pytest -v  # The -v flag is for verbose output
